#!/usr/bin/env python3
import os, sys

# A python script that converts typed ascii pinyin to actual unicode pinyin.

U_DOT = 252

def toPinyin(order,letter):
    if order == '1':
        if letter == 'a':
            return chr(257)
        elif letter == 'e':
            return chr(275)
        elif letter == 'i':
            return chr(299)
        elif letter == 'o':
            return chr(333)
        elif letter == 'u':
            return chr(363)
        elif letter == chr(U_DOT):
            return chr(470)

    elif order == '2':
        if letter == 'a':
            return chr(225)
        elif letter == 'e':
            return chr(233)
        elif letter == 'i':
            return chr(237)
        elif letter == 'o':
            return chr(243)
        elif letter == 'u':
            return chr(250)
        elif letter == chr(U_DOT):
            return chr(472)

    elif order == '3':
        if letter == 'a':
            return chr(462)
        elif letter == 'e':
            return chr(283)
        elif letter == 'i':
            return chr(464)
        elif letter == 'o':
            return chr(466)
        elif letter == 'u':
            return chr(468)
        elif letter == chr(U_DOT):
            return chr(474)

    elif order == '4':
        if letter == 'a':
            return chr(224)
        elif letter == 'e':
            return chr(232)
        elif letter == 'i':
            return chr(236)
        elif letter == 'o':
            return chr(242)
        elif letter == 'u':
            return chr(249)
        elif letter == chr(U_DOT):
            return chr(476)

    return None

def asciiToPinyin(text):
    output = ''
    checkNext = False
    prevchar = ''
    for x in text:
        if checkNext == False:
            if x == 'a' or x == 'e' or x == 'i' or x == 'o' or x == 'u':
                checkNext = True
            else:
                output += x
        else:
            checkNext = False
            if prevchar == 'u' and x == ':':
                x = chr(U_DOT)
                checkNext = True
            else:
                pinyin = toPinyin(x, prevchar)
                if pinyin == None:
                    output += prevchar
                    if x == 'a' or x == 'e' or x == 'i' or x == 'o' or x == 'u':
                        checkNext = True
                    else:
                        output += x
                else:
                    output += pinyin
        prevchar = x

    if checkNext == True:
        output += prevchar
    return output

def main():
    # Interactive mode: read from arguments.
    # Non-Interactive mode: read from stdin.
    if os.isatty(sys.stdin.fileno()):
        output_str = asciiToPinyin( ' '.join(sys.argv[1:]) )
        print(output_str) # Want a newline.
    else:
        output_str = asciiToPinyin( sys.stdin.read() )
        sys.stdout.write(output_str) # No newline.


if __name__ == '__main__':
    main()
